### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CodyEdition** [Chris24T/RimLists#1] opened 2023-03-11 16:47 UTC
Requirements
- Installed 

Error
- Getting errors after input fields

OS
- Windows 11 22H2
```
Enter modlist save location path (leave empty for auto-resolve RimPy Modlists folder):
     C:\Users\Node Next\AppData\LocalLow\RimPy Mod Manager\ModLists
Traceback (most recent call last):
  File "C:\Users\Node Next\Documents\Rimlist.py", line 212, in <module>
    package_ids = findModPackageIds(entries)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Node Next\Documents\Rimlist.py", line 167, in findModPackageIds
    tree = ET.parse(about_path)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Node Next\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "C:\Users\Node Next\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 23, column 522
```

**Comment by Chris24T** [comment] 2023-03-11 17:56
Thanks for making the issue and helping out.

This looks like a specific mod's _About.xml_ is mal-formed or potentially an issue with the ET library and uncaught escape/invalid characters - not necessarily an issue with the script. Ill take a closer look either way, and at the least add some better error handling here to show which mod is "bad", and an option to skip it.

Could you possibly share the modlist you are using (or wait me for to do the above, and then provide just the erroneous mod's id), as chances are the issue is one of the mods from there. Then i should be able to identify why it is malformed and provide a fix.

**Comment by Chris24T** [comment] 2023-03-11 18:16
The relevant temporary fix has been made, you should be able to build your modlist, and it not be aborted due to the "bad" mod (but of course the bad mod is excluded from the resulting list - you may have to add it back manually). 

If you want me to look into this further, please provide the modlist url or the mod id of the broken mod. The broken mod's id should now be found in the console when running the script.

**Comment by Chris24T** [comment] 2023-03-13 19:57
Closing until relevant data is provided.

**Closed as completed by Chris24T** 2023-03-13 19:57 UTC
